name: Android Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip "*.zip" -d project

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmond +x project/gradlew

      - name: Build APK
        run: cd project && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyTube-APK
          path: project/app/build/outputs/apk/degub/*.apk
